export const EXPERIENCE_CONSTANTS = {
  EXP_1: {
    id: 'exp-1',
    positionKey: 'experience.positions.juniorProg',
    functions: [
      'experience.exp-1.func-1',
      'experience.exp-1.func-2',
      'experience.exp-1.func-3',
      'experience.exp-1.func-4',
      'experience.exp-1.func-5',
      'experience.exp-1.func-6',
      'experience.exp-1.func-7',
      'experience.exp-1.func-8',
    ] as const,
  },
  EXP_2: {
    id: 'exp-2',
    positionKey: 'experience.positions.juniorLaravelDev',
    functions: [
      'experience.exp-2.func-1',
      'experience.exp-2.func-2',
      'experience.exp-2.func-3',
      'experience.exp-2.func-4',
      'experience.exp-2.func-5',
      'experience.exp-2.func-6',
      'experience.exp-2.func-7',
      'experience.exp-2.func-8',
    ] as const,
  },
  EXP_3: {
    id: 'exp-3',
    positionKey: 'experience.positions.JuniorDev',
    functions: [
      'experience.exp-3.func-1',
      'experience.exp-3.func-2',
      'experience.exp-3.func-3',
      'experience.exp-3.func-4',
      'experience.exp-3.func-5',
      'experience.exp-3.func-6',
      'experience.exp-3.func-7',
      'experience.exp-3.func-8',
      'experience.exp-3.func-9',
      'experience.exp-3.func-10',
    ] as const,
  },
  EXP_4: {
    id: 'exp-4',
    positionKey: 'experience.positions.juniorLaravelDev',
    functions: [
      'experience.exp-4.func-1',
      'experience.exp-4.func-2',
      'experience.exp-4.func-3',
      'experience.exp-4.func-4',
      'experience.exp-4.func-5',
      'experience.exp-4.func-6',
      'experience.exp-4.func-7',
      'experience.exp-4.func-8',
      'experience.exp-4.func-9',
      'experience.exp-4.func-10',
    ] as const,
  },
  EXP_5: {
    id: 'exp-5',
    positionKey: 'experience.positions.seniorLaravelDev',
    functions: [
      'experience.exp-5.func-1',
      'experience.exp-5.func-2',
      'experience.exp-5.func-3',
      'experience.exp-5.func-4',
      'experience.exp-5.func-5',
      'experience.exp-5.func-6',
      'experience.exp-5.func-7',
      'experience.exp-5.func-8',
      'experience.exp-5.func-9',
      'experience.exp-5.func-10',
      'experience.exp-5.func-11',
      'experience.exp-5.func-12',
      'experience.exp-5.func-13',
    ] as const,
  },
  EXP_6: {
    id: 'exp-6',
    positionKey: 'experience.positions.seniorNETDev',
    functions: [
      'experience.exp-6.func-1',
      'experience.exp-6.func-2',
      'experience.exp-6.func-3',
      'experience.exp-6.func-4',
      'experience.exp-6.func-5',
      'experience.exp-6.func-6',
      'experience.exp-6.func-7',
      'experience.exp-6.func-8',
      'experience.exp-6.func-9',
    ] as const,
  },
  EXP_7: {
    id: 'exp-7',
    positionKey: 'experience.positions.seniorDev',
    functions: [
      'experience.exp-7.func-1',
      'experience.exp-7.func-2',
      'experience.exp-7.func-3',
      'experience.exp-7.func-4',
      'experience.exp-7.func-5',
      'experience.exp-7.func-6',
      'experience.exp-7.func-7',
      'experience.exp-7.func-8',
      'experience.exp-7.func-9',
      'experience.exp-7.func-10',
    ] as const,
  },
  EXP_8: {
    id: 'exp-8',
    positionKey: 'experience.positions.ingDev',
    functions: [
      'experience.exp-8.func-1',
      'experience.exp-8.func-2',
      'experience.exp-8.func-3',
      'experience.exp-8.func-4',
      'experience.exp-8.func-5',
      'experience.exp-8.func-6',
      'experience.exp-8.func-7',
      'experience.exp-8.func-8',
      'experience.exp-8.func-9',
      'experience.exp-8.func-10',
      'experience.exp-8.func-11',
      'experience.exp-8.func-12',
      'experience.exp-8.func-13',
    ] as const,
  },
  EXP_9: {
    id: 'exp-9',
    positionKey: 'experience.positions.seniorDev',
    functions: [
      'experience.exp-9.func-1',
      'experience.exp-9.func-2',
      'experience.exp-9.func-3',
      'experience.exp-9.func-4',
      'experience.exp-9.func-5',
      'experience.exp-9.func-6',
      'experience.exp-9.func-7',
      'experience.exp-9.func-8',
      'experience.exp-9.func-9',
      'experience.exp-9.func-10',
      'experience.exp-9.func-11',
    ] as const,
  },
} as const;

/**
 * Tipo derivado de las constantes para type safety
 */
export type ExperienceConstant = typeof EXPERIENCE_CONSTANTS;

/**
 * Tipo de las claves de experiencias para type safety
 */
export type ExperienceKey = keyof typeof EXPERIENCE_CONSTANTS;
