name: Deploy Angular with GitHub Pages
on:
  push:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install deps
        run: npm i
      - name: Build app bundle
        run: npm run build-portfolio
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist/portfolio-angular/browser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
