name: Deploy Angular with GitHub Pages

on:
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v3.7.0
        with:
          node-version: "18"
      - name: Install deps
        run: npm i
      - name: Build app bundle
        run: npm run build-portfolio
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist/portfolio-angular
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
